geekshop_server/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from orders.views import OrderList, order_forming_complete, OrderItemsCreate, OrderRead, OrderItemsUpdate, OrderDelete

app_name = 'orders'

urlpatterns = [
    path('', login_required(OrderList.as_view()), name='orders_list'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', login_required(OrderItemsCreate.as_view()), name='order_create'),
    path('read/<int:pk>/', login_required(OrderRead.as_view()), name='order_read'),
    path('update/<int:pk>/', login_required(OrderItemsUpdate.as_view()), name='order_update'),
    path('delete/<int:pk>/', login_required(OrderDelete.as_view()), name='order_delete'),
]

users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/(<email>)/(<activation_key>)/', verify, name='verify'),
]

orders/models.py
from django.db import models
from products.models import Product
from django.conf import settings

class Order(models.Model):

    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)
    is_active = models.BooleanField(db_index=True, default=True)

    def get_product_cost(self):
        return self.product.price * self.quantity

orders/forms.py
from django import forms
from orders.models import Order, OrderItem
from products.models import Product


class OrderForm(forms.ModelForm):
   class Meta:
       model = Order
       exclude = ('user',)

   def __init__(self, *args, **kwargs):
       super(OrderForm, self).__init__(*args, **kwargs)
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='Цена', required=False)

    class Meta:
       model = OrderItem
       exclude = ()

    def __init__(self, *args, **kwargs):
       super(OrderItemForm, self).__init__(*args, **kwargs)
       self.fields['product'].queryset = Product.objects.select_related()
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'

orders/views.py
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from baskets.models import Basket
from orders.models import Order, OrderItem
from orders.forms import OrderItemForm


class OrderList(ListView):
   model = Order

   def get_queryset(self):
       return Order.objects.select_related().filter(user=self.request.user)

class OrderItemsCreate(CreateView):
   model = Order
   fields = []
   success_url = reverse_lazy('orders:orders_list')

   def get_context_data(self, **kwargs):
       data = super(OrderItemsCreate, self).get_context_data(**kwargs)
       OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

       if self.request.POST:
           formset = OrderFormSet(self.request.POST)
       else:
           basket_items = Basket.objects.select_related().filter(user=self.request.user)
           if len(basket_items):
               OrderFormSet = inlineformset_factory(Order, OrderItem,
                                  form=OrderItemForm, extra=len(basket_items))
               formset = OrderFormSet()
               for num, form in enumerate(formset.forms):
                   form.initial['product'] = basket_items[num].product
                   form.initial['quantity'] = basket_items[num].quantity
                   form.initial['price'] = basket_items[num].product.price
               basket_items.delete()
           else:
               formset = OrderFormSet()

       data['orderitems'] = formset
       return data

   def form_valid(self, form):
       context = self.get_context_data()
       orderitems = context['orderitems']

       with transaction.atomic():
           form.instance.user = self.request.user
           self.object = form.save()
           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

       # удаляем пустой заказ
       if self.object.get_total_cost() == 0:
           self.object.delete()

       return super(OrderItemsCreate, self).form_valid(form)

class OrderItemsUpdate(UpdateView):
   model = Order
   fields = []
   success_url = reverse_lazy('orders:orders_list')

   def get_context_data(self, **kwargs):
       data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
       OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

       if self.request.POST:
           data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
       else:
           queryset = self.object.orderitems.select_related()
           formset = OrderFormSet(instance=self.object, queryset=queryset)
           for form in formset.forms:
               if form.instance.pk:
                   form.initial['price'] = form.instance.product.price
           data['orderitems'] = formset
       return data

   def form_valid(self, form):
       context = self.get_context_data()
       orderitems = context['orderitems']

       with transaction.atomic():
           self.object = form.save()
           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

       # удаляем пустой заказ
       if self.object.get_total_cost() == 0:
           self.object.delete()

       return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
   model = Order
   success_url = reverse_lazy('orders:orders_list')

class OrderRead(DetailView):
   model = Order

   def get_context_data(self, **kwargs):
       context = super(OrderRead, self).get_context_data(**kwargs)
       context['title'] = 'заказ/просмотр'
       return context

def order_forming_complete(request, pk):
   order = get_object_or_404(Order, pk=pk)
   order.status = Order.SENT_TO_PROCEED
   order.save()

   return HttpResponseRedirect(reverse('orders:orders_list'))

@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
   if update_fields is 'quantity' or 'product':
       if instance.pk:
           instance.product.quantity -= instance.quantity - \
                                        sender.get_item(instance.pk).quantity
       else:
           instance.product.quantity -= instance.quantity
       instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
   instance.product.quantity += instance.quantity
   instance.product.save()

orders/templates/orders/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>
<body>
  <div class="order_container">
       {% block content %}

       {% endblock %}

  </div>
</body>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/order.js' %}"></script>
</html>

orders/templates/orders/order_confirm_delete.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'orders/includes/inc_order_summary.html' %}
       <form action="{% url 'orders:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}
   {% include 'orders/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'orders/includes/inc_order_actions.html' %}

{% endblock %}

orders/templates/orders/order_form.html
{% extends 'orders/base.html' %}
{% load static %}
{% load cache %}

{% block content %}
   {% include 'orders/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                               {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                               {%  endif %}

                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name != 'price' %}
                                   {{ field }}
                               {% else %}
                                   {% if field.value %}
                                       <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                         {{ field.value }}
                                       </span> руб
                                   {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'orders/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

orders/templates/orders/order_list.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}
   <div class="h2 text-center head">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'orders:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'orders:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'orders:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'index' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'orders:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}