geekshop_server/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from orders.views import OrderList, order_forming_complete, OrderItemsCreate, OrderRead, OrderItemsUpdate, OrderDelete

app_name = 'orders'

urlpatterns = [
    path('', login_required(OrderList.as_view()), name='orders_list'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', login_required(OrderItemsCreate.as_view()), name='order_create'),
    path('read/<int:pk>/', login_required(OrderRead.as_view()), name='order_read'),
    path('update/<int:pk>/', login_required(OrderItemsUpdate.as_view()), name='order_update'),
    path('delete/<int:pk>/', login_required(OrderDelete.as_view()), name='order_delete'),
]

products/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('products/', cache_page(3600) (views.ProductList.as_view()), name='products'),
    # path('page/<int:page>/', views.products, name='page'),

]

users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/(<email>)/(<activation_key>)/', verify, name='verify'),
]

products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Название', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(verbose_name='Название', max_length=256)
    image = models.ImageField(verbose_name='Фото', upload_to='products_images', blank=True, null=True)
    description = models.CharField(verbose_name='Описание', max_length=64, blank=True, null=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return f'{self.name} | {self.category.name}'

products/forms.py
from django import forms

products/views.py
import random
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from products.models import ProductCategory, Product
from django.conf import settings
from django.core.cache import cache

def get_links_menu():
   if settings.LOW_CACHE:
       key = 'links_menu'
       links_menu = cache.get(key)
       if links_menu is None:
           links_menu = ProductCategory.objects.filter(is_active=True)
           cache.set(key, links_menu)
       return links_menu
   else:
       return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
   if settings.LOW_CACHE:
       key = f'category_{pk}'
       category = cache.get(key)
       if category is None:
           category = get_object_or_404(ProductCategory, pk=pk)
           cache.set(key, category)
       return category
   else:
       return get_object_or_404(ProductCategory, pk=pk)


def get_products():
   if settings.LOW_CACHE:
       key = 'products'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
   if settings.LOW_CACHE:
       key = f'product_{pk}'
       product = cache.get(key)
       if product is None:
           product = get_object_or_404(Product, pk=pk)
           cache.set(key, product)
       return product
   else:
       return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
   if settings.LOW_CACHE:
       key = 'products_orederd_by_price'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
   if settings.LOW_CACHE:
       key = f'products_in_category_orederd_by_price_{pk}'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

def get_hot_product():
   products = get_products()

   return random.sample(list(products), 1)[0]

# index
@login_required
def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'products/index.html', context)

# contact
@login_required
def contact(request):
    context = {'title': 'GeekShop - Контакты'}
    return render(request, 'products/contact.html', context)

# products
class ProductList(ListView):
    model = Product
    context_object_name = "products"
    template_name = 'products/products.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop - Каталог'
        context['categories'] = ProductCategory.objects.all()
        context['links_menu'] = get_links_menu()
        return context

    def get_queryset(self):
        category_id = self.kwargs.get('category_id', '')
        q = super().get_queryset()
        if category_id:
            category = get_category(category_id)
            result = get_products_in_category_orederd_by_price(category_id)
        else:
            result = get_products_orederd_by_price()
        return result

products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
               {% if user.is_authenticated %}
                <li class="nav-item dropdown">

                       <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-layouts" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                            <span class="caret"></span>
                       </a>
                       <div class="dropdown-menu" aria-labelledby="topnav-layouts">
                                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль
                                    <i class="fas fa-user-circle"></i>
                                </a>
                                <a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы
                                    <i class="fas fa-user-circle"></i>
                                </a>
                            {% if user.is_staff %}
                                <a class="dropdown-item" href="{% url 'admins:index' %}">Администрирование
                                    <i class="fas fa-users-cog"></i>
                                </a>
                            {% endif %}
                                <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти
                                    <i class="fas fa-sign-out-alt"></i>
                                </a>
                       </div>


                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти
                        <i class="fas fa-sign-in-alt"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/basket.js' %}"></script>

</body>
</html>

products/templates/products/contact.html
{% extends "products/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
		<div class="hero">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'index' %}">домой</a></li>
					<li><a href="{% url 'products' %}">продукты</a></li>
					<li><a href="{% url 'contact' %}" class="active">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="#" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <button id="add_{{ product.id }}" class="btn btn-outline-success">Отправить в корзину</button>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>

                   <nav aria-label="Page navigation example">
                      {% if is_paginated %}

                      <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                          <a class="page-link" href="#">&laquo;</a>
                        </li>
                        {% endif %}

                          {% for i in paginator.page_range %}

                          {% if page_obj.number == i %}
                        <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                        {% else %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                        {% endif %}

                          {% endfor %}

                          {% if page_obj.has_next %}
                        <li class="page-item">
                          <a href="?page={{page_obj.next_page_number}}" class="page-link">&raquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                          <a class="page-link">&raquo;</a>
                        </li>
                        {% endif %}

                      </ul>


                      {% endif %}
                    </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
        </div>
    </footer>
{% endblock %}